<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
  
    <PackageReference Include="Glacier.Inference" Version="1.2.19" />
    <PackageReference Include="Glacier.Tune" Version="1.0.5" />
    <PackageReference Include="Glacier.Serve" Version="1.1.2" />
    <PackageReference Include="Glacier.Rag" Version="1.0.3" />
    <PackageReference Include="Glacier.Gpu" Version="1.0.8" />
  </ItemGroup>

  <ItemGroup Condition="Exists('..\Glacier.Polaris\src\Glacier.Polaris\Glacier.Polaris.csproj')">
    <ProjectReference Include="..\Glacier.Polaris\src\Glacier.Polaris\Glacier.Polaris.csproj" />
    <ProjectReference Include="..\Glacier.Vector\src\Glacier.Vector\Glacier.Vector.csproj" />
    <ProjectReference Include="..\Glacier.ML\src\Glacier.ML\Glacier.ML.csproj" />
    <ProjectReference Include="..\Glacier.Tensor\src\Glacier.Tensor\Glacier.Tensor.csproj" />
    <ProjectReference Include="..\Glacier.Plot\src\Glacier.Plot\Glacier.Plot.csproj" />
    <ProjectReference Include="..\Glacier.StatsViz\src\Glacier.StatsViz\Glacier.StatsViz.csproj" />
    <ProjectReference Include="..\AgentDevKit.Adk\src\AgentDevKit.Adk\AgentDevKit.Adk.csproj" />
    <ProjectReference Include="..\tinypdf-csharp\src\TinyPdf\TinyPdf.csproj" />
    <ProjectReference Include="..\Glacier.DocTree\src\Glacier.DocTree\Glacier.DocTree.csproj" />
    <ProjectReference Include="..\Glacier.Graph\src\Glacier.Graph\Glacier.Graph.csproj" />
  </ItemGroup>
  <ItemGroup Condition="!Exists('..\Glacier.Polaris\src\Glacier.Polaris\Glacier.Polaris.csproj')">
    <PackageReference Include="Glacier.Polaris" Version="1.0.20" />
    <PackageReference Include="Glacier.Vector" Version="1.0.7" />
    <PackageReference Include="Glacier.ML" Version="1.0.4" />
    <PackageReference Include="Glacier.Tensor" Version="1.0.9" />
    <PackageReference Include="Glacier.Plot" Version="1.0.5" />
    <PackageReference Include="Glacier.StatsViz" Version="1.0.4" />
    <PackageReference Include="Glacier.DocTree" Version="1.0.5" />
    <PackageReference Include="Glacier.Graph" Version="1.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>1.0.1</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>47cdd2e8-4238-4e3b-8228-d39795881c39</UserSecretsId>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests\**</DefaultItemExcludes>
  </PropertyGroup>

</Project>
